---
title: "TU Datamining HW 1"
author: "Ann Marie Finley"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: false
    toc_float:
      collapsed: false
      smooth_scroll: false
    df_print: paged
    css: jamie_mod4.css
---

```{r setup, include=FALSE, cache=T}
knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.align = 'center', fig.path='Figs/', echo=TRUE, tidy=TRUE, message=F, warning=F, cache=T)
```

```{r echo=FALSE, message=FALSE}
library(tidyverse)
```

# Homework Question One
```{r}
# Generate and print a sequence of letters A to X, repeated three times
letters <- letters[1:24] #This produces a squence named "letters" consisting of letters A through X
rep(letters,3) #This prints the above sequence, "letters" three times
```


# Homework Question Two
```{r}
# Randomly sample 20 numbers from a possible range of 1-100, without replacement
set.seed(57) #set seed for reproducibility in random number sample. If this was not here, the 20 numbers randomly selected would be different each time I knit
series1 <- sample(1:100, 20, replace = FALSE)  #This specifies that a sample of 20 numbers from 1-100 should be sampled without replacement
print(series1) #Print the above

```

# Homework Question Three
```{r}
# Print a sequence from 1:100 by 2's
series2 <- seq(1, 100, by=2) #This creates a number sequence from 1 to 100, by 2's. The sequence will start from 1, so in this case, "by 2's" will produce odd numbers.
print(series2) #Print the above
```


