---
title: "TU Datamining Assignment 1"
author: "Ann Marie Finley"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: false
    toc_float:
      collapsed: false
      smooth_scroll: false
    df_print: paged
    css: jamie_mod4.css
---

```{r setup, include=FALSE, cache=T}
knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.align = 'center', fig.path='Figs/', echo=FALSE, tidy=TRUE, message=F, warning=F, cache=T)
```

```{r echo=FALSE, message=FALSE}
library(tidyverse)
```

# In Class
## Practice in Class
Is Jane Austen any good? 
```{recho=FALSE, message=FALSE}
#generate random series of 100 numbers between 0-100
series1 <- runif(100, min = 0, max = 100)   # notably, this does not give integers
print(series1)

# generate n random numbers between 0 and 100 (without replacement)
series2 <- sample(0:100, 100, replace = FALSE)  #this does give integers
print(series2)

# done in class together, printing sequence
jane <- seq(1:10) #generate a sequence of nubmers from one to ten
print(jane)

# repeat jane three times
thrice <- rep(jane, 3) #rep(something, X times)
print(thrice) 

# jane times two
austen <- jane*2
print(austen)

```

#Homework 1
```{r echo=FALSE, message=FALSE}
# Generate and print a sequence of letters A to X, repeated three times
letters <- letters[1:24]
rep(letters,3)

```

#Homework 2
```{r echo=FALSE, message=FALSE}
# Randomly sample 20 numbers from a possible range of 1-100, without replacement
series3 <- sample(0:100, 20, replace = FALSE)  
print(series3)

squared <- series3*2
print(squared)

cubed <- series3*3
print(cubed)


```

#Homework 3
```{r echo=FALSE, message=FALSE}
# Print a sequence from 1:100 by 2's
series4 <- seq(1, 100, by=2)
print(series4)
```


# Non-Fiction
## Bill Bryson
Does the schtick get old?

```{r}
x <- sample(100, 100) #sample from 1 to 100, 100 times no replacement
y <- sample (100, 100)
z <- data.frame(x,y)  #combine variables x and y into a single dataframe
plot(z$x, z$y, col="red") # plot them, the $ is needed to index
```

##Jared Diamond
Isn't he just a little boring?



